-- Create matches table for realtime score tracking
CREATE TABLE IF NOT EXISTS public.matches (
  id bigint PRIMARY KEY,             -- Use Match ID from Challonge
  tournament_id bigint NOT NULL,
  player1_id bigint,
  player2_id bigint,
  score_csv text,                    -- Score format e.g. "1-0"
  state text,                        -- open, pending, complete
  winner_id bigint,                  -- Winner ID
  identifier text,                   -- Match identifier (e.g. "A", "B", "1")
  round int,                         -- Round number
  suggested_play_order int,          -- Play order
  underway_at timestamp with time zone,
  completed_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Enable Realtime for matches
ALTER PUBLICATION supabase_realtime ADD TABLE public.matches;

-- Create registrations table
CREATE TABLE IF NOT EXISTS public.registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_name text NOT NULL,
  beyblade_combo text,
  room_id text,
  challonge_participant_id bigint,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Enable RLS (Row Level Security) - Optional but recommended
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;

-- Creating simple policies for public read access (adjust as needed for production)
CREATE POLICY "Public read access for matches" ON public.matches
  FOR SELECT USING (true);

CREATE POLICY "Public read access for registrations" ON public.registrations
  FOR SELECT USING (true);
